name: Release

on:
  push:
    branches:
      - main
      - develop

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures

      - name: Run tests
        run: npx nx run-many -t lint test build typecheck

      - name: Build packages
        run: npx nx run-many -t build --parallel=3

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

  # Job para notificar sobre falhas
  notify-failure:
    name: Notify Failure
    runs-on: ubuntu-latest
    needs: release
    if: failure()
    steps:
      - name: Notify failure
        run: |
          echo "Release workflow failed. Please check the logs."
          echo "Commit: ${{ github.sha }}"
          echo "Branch: ${{ github.ref_name }}"
